language: csharp
solution: SAP1EMU.sln
mono: none
dotnet: 3.1
script:
  - dotnet build SAP1EMU.sln
  - dotnet add package coverlet.collector
  - dotnet test SAP1EMU.Lib.Test -v n --no-build --collect:"XPlat Code Coverage"
  - dotnet test SAP1EMU.CLI.Test -v n --no-build --collect:"XPlat Code Coverage"
  - dotnet test SAP1EMU.Assembler.Test -v n --no-build --collect:"XPlat Code Coverage"
  - dotnet test SAP1EMU.Engine.Test -v n --no-build --collect:"XPlat Code Coverage"

after_success:
  # - cd SAP1EMU.Lib.Test/
  # - dotnet add package coverlet.collector
  # - dotnet test --collect:"XPlat Code Coverage"

  # - cd ..
  # - cd SAP1EMU.Engine.Test/
  # - dotnet test --collect:"XPlat Code Coverage"

  # - cd ..
  # - cd SAP1EMU.Assembler.Test/
  # - dotnet test --collect:"XPlat Code Coverage"

  # - cd ..
  # - cd SAP1EMU.CLI.Test/
  # - dotnet test --collect:"XPlat Code Coverage"

  - bash <(curl -s https://codecov.io/bash)
