language: csharp
solution: SAP1EMU-no-gui.sln
mono: none
dotnet: 3.1
script:
  - dotnet build SAP1EMU-no-gui.sln
  - dotnet test SAP1EMU-no-gui.sln
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
